### ISSUE TITLE
Question: Connect turntable manually from Windows with Putty terminal?

### ISSUE THREAD

**Issue by mrcg** [opensourcemanufacturing/Revopoint-Dual-Turntable#1]
Hello!
I have connected the Revopoint Dual Axis turntable successfully via BT to my Win11 PC.
In the BT settings it shows up as "connected". Revo SW is not installed.
Unfortunately i cannot find the com port to connect via putty.
How is it possible to connect to turntable using terminal editor or DOS cmd?
Thanks
Chris

**Comment by X3msnake** [comment]
No idea if that is even possible, sorry.

But surely there is some PC apps already available for this, try searching the official forum

**Comment by X3msnake** [comment]
https://github.com/eXplOiD1/Revopoint-Dual-Axis-Turntable-webbased-Controller
